Repository thesaas-company/xray, pull requests merged in 2024-05, with the labels that each got.

#11 Added support for MongoDB and fixed bugs in redshift
  client.go
  databases/redshift/redshift.go
  example/redshift/main.go
  go.mod
  go.sum
  types/types.go
Labels: 1 min review

#12 Fixed bugs in snowflake and updated bigquery example
  databases/snowflake/snowflake.go
  databases/snowflake/snowflake_test.go
  example/bigquery/main.go
  example/snowflake/main.go
Labels: 1 min review

#13 Added docs
  README.md
  client.go
  config/config.go
  databases/bigquery/bigquery.go
  databases/bigquery/bigquery_test.go
  databases/mysql/mysql.go
  databases/mysql/mysql_test.go
  databases/postgres/postgres.go
  databases/postgres/postgres_test.go
  databases/redshift/redshift.go
  databases/redshift/redshift_test.go
  databases/snowflake/snowflake.go
  databases/snowflake/snowflake_test.go
  example/bigquery/main.go
  go.mod
  go.sum
  logger/logger.go
  types/types.go
Labels: 10 min review

#14 added create table Interface in ISQL
  README.md
  databases/bigquery/bigquery.go
  databases/bigquery/bigquery_test.go
  databases/mysql/mysql.go
  databases/mysql/mysql_test.go
  databases/postgres/postgres.go
  databases/postgres/postgres_test.go
  databases/redshift/redshift.go
  databases/redshift/redshift_test.go
  databases/snowflake/snowflake.go
  databases/snowflake/snowflake_test.go
  example/bigquery/main.go
  example/mysql/main.go
  example/postgres/main.go
  example/redshift/main.go
  example/snowflake/main.go
  logger/logger.go
  types/types.go
Labels: 30 min review

#21 Added CLI
  .golangci.yml
  .goreleaser.yml
  Makefile
  buf.gen.yaml
  cli/cmd/root.go
  cli/main.go
  config.yaml
  go.mod
  go.sum
  idl/buf.md
  idl/buf.yaml
  idl/xray/v1/xray.proto
  pixi.lock
  types/types.go
Labels: 20 min review

#22 upgraded bigquery using sql client
  .golangci.yml
  cli/cmd/root.go
  cli/main.go
  client.go
  config/config.go
  databases/bigquery/bigquery.go
  databases/bigquery/bigquery_test.go
  databases/mysql/mysql.go
  databases/mysql/mysql_test.go
  databases/postgres/postgres.go
  databases/postgres/postgres_test.go
  databases/redshift/redshift.go
  databases/snowflake/snowflake.go
  databases/snowflake/snowflake_test.go
  example/bigquery/main.go
  example/postgres/main.go
  example/redshift/main.go
  go.mod
  go.sum
  logger/logger.go
  types/types.go
Labels: 30 min review

#24 fix lint
  .golangci.yml
  databases/bigquery/bigquery.go
  databases/bigquery/bigquery_test.go
  databases/mysql/mysql.go
  databases/mysql/mysql_test.go
  databases/postgres/postgres.go
  databases/postgres/postgres_test.go
  databases/snowflake/snowflake.go
  databases/snowflake/snowflake_test.go
Labels: 5 min review

#25 fix redshift integration
  databases/redshift/redshift.go
  example/redshift/main.go
  go.mod
  go.sum
Labels: 5 min review

#26 added support for mssql
  client.go
  config/config.go
  databases/mssql/mssql.go
  databases/mssql/mssql_test.go
  example/mssql/main.go
  go.mod
  go.sum
  types/types.go
Labels: 20 min review

#27 Ready for Production
  README.md
  cli/cmd/root.go
  client.go
  config/config.go
  databases/bigquery/bigquery.go
  databases/bigquery/bigquery_test.go
  databases/mssql/mssql.go
  databases/mssql/mssql_test.go
  databases/mysql/mysql.go
  databases/mysql/mysql_test.go
  databases/postgres/postgres.go
  databases/postgres/postgres_test.go
  databases/redshift/redshift.go
  databases/redshift/redshift_test.go
  databases/snowflake/snowflake.go
  databases/snowflake/snowflake_test.go
  example/bigquery/integration.md
  example/bigquery/main.go
  example/mssql/README.md
  example/mssql/integration.md
  example/mssql/main.go
  example/mysql/README.md
  example/mysql/integration.md
  example/mysql/main.go
  example/postgres/README.md
  example/postgres/integration.md
  example/postgres/main.go
  example/redshift/README.md
  example/redshift/integration.md
  example/redshift/main.go
  example/snowflake/README.md
  example/snowflake/integration.md
  example/snowflake/main.go
  go.mod
  logger/logger.go
  types/types.go
Labels: 30 min review

#28 Added docs to cli
  cli/cmd/root.go
Labels: 1 min review

#29 Handled postgres meta commands
  cli/cmd/root.go
Labels: 5 min review

#30 Added Base64 decoding
  cli/cmd/root.go
  databases/bigquery/bigquery.go
  databases/mysql/mysql.go
  databases/mysql/mysql_test.go
  databases/postgres/postgres.go
  databases/redshift/redshift.go
  databases/snowflake/snowflake.go
  go.mod
  go.sum
  types/types.go
Labels: 10 min review

#31 Fixed Redshift test case
  databases/bigquery/bigquery_test.go
  databases/redshift/redshift_test.go
Labels: 1 min review

#32 Tested and fixed base64 decoding issue
  cli/cmd/root.go
  databases/mysql/mysql.go
  databases/postgres/postgres.go
Labels: 10 min review

#34 fixed bigquery schema bug
  databases/bigquery/bigquery.go
  databases/bigquery/bigquery_test.go
  go.mod
  go.sum
Labels: 1 min review

#35 Updated mssql docs and added docker run command for local setup
  example/mssql/README.md
Labels: 1 min review

#36 Added docs for CLI
  README.md
  cli/README.md
  databases/mysql/mysql_test.go
  go.mod
  go.sum
Labels: 10 min review
